chatwoot:
  postgresql:
    enabled: false
    auth:
      database: "chatwoot"
      postgresPassword: "12345"
      username: "root"
  redis:
    enabled: true
    auth:
        password: redis
    master:
        persistence:
            enabled: true
    replica:
        replicaCount: 1