redis:
  architecture: standalone
  auth:
    enabled: true
    existingSecret: redis-secret
    existingSecretPasswordKey: redis-password
  replica:
    replicaCount: 3  # Número de réplicas (sin contar el master)
  master:
    count: 1  # Número de instancias del master
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"
  configmap:
    redis.conf: |
      databases 2