apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://charts.bitnami.com/bitnami"  # URL del repo Helm
    chart: redis
    targetRevision: "17.3.2"  # Versión del chart
    helm:
      values: |  # Aquí van los valores personalizados de Helm
        architecture: standalone
        auth:
          enabled: true
          existingSecret: redis-secret
          existingSecretPasswordKey: redis-password
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
  destination:
    server: https://kubernetes.default.svc
    namespace: restaurant-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true