# apiVersion: v1
# kind: Secret
# metadata:
#   name: redis-secret
#   annotations:
#     argocd.argoproj.io/sync-wave: "-1"
# type: Opaque
# data:
#   redis-password: dTZKVngwczJTRg== # Base64 de "u6JVx0s2SF"