chatwoot:
  postgresql:
    enabled: false
    auth:
      database: "chatwoot"
      postgresPassword: "12345"
      username: "root"
  redis:
    enabled: true
    # auth:
    #   host: "restaurant-dev-redis-master"
    #   password: "u6JVx0s2SF"
    # database: 1
  persistence:
    enabled: true
    storageClass: "standard"  # Reemplaza si utilizas otro StorageClass
    accessMode: "ReadWriteOnce"
    size: 10Gi 