# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: n8n-worker
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: n8n-worker
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: n8n-worker
#   template:
#     metadata:
#       labels:
#         app: n8n-worker
#     spec:
#       containers:
#       - name: n8n
#         image: n8nio/n8n:latest
#         envFrom:
#           - configMapRef:
#               name: n8n-config
#         env:
#           - name: QUEUE_BULL_REDIS_PASSWORD
#             valueFrom:
#               secretKeyRef:
#                 name: redis-secret
#                 key: redis-password
#         command: ["n8n", "worker"]