apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: restaurant
  namespace: argocd
spec:
    generators:
    - list:
        elements:
          - env: dev
            namespace: restaurant-dev
            valuesFiles:
              - n8n-values-dev.yaml
          - env: prod
            namespace: restaurant-prod
            valuesFiles:
              - n8n-values-prod.yaml
    template:
      metadata:
        name: my-app-{{env}}
      spec: 
        project: default
        source:
          repoURL: "https://github.com/lchavezpozo/MeeseeksCluster"
          path: Apps/Restaurant
          targetRevision: main
        destination:
          server: https://kubernetes.default.svc
          namespace: "{{namespace}}"
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
        namespaceResource:
          create: true