apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: restaurant
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            namespace: restaurant-dev
          # - env: prod
          #   namespace: restaurant-prod
  template:
    metadata:
      name: restaurant-{{env}}
    spec:
      project: default
      source:
        repoURL: "https://github.com/lchavezpozo/MeeseeksCluster"
        path: Apps/Restaurant
        targetRevision: main
        helm:
          valueFiles:
            - "values/{{env}}/n8n-values-{{env}}.yaml"
            - "values/{{env}}/postgres-values-{{env}}.yaml"
            - "values/{{env}}/redis-values-{{env}}.yaml"
            - "values/{{env}}/evolution-values-{{env}}.yaml"
            - "values/{{env}}/chatwoot-values-{{env}}.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true