apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: restaurant-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/lchavezpozo/MeeseeksCluster"
    path: Apps/Restaurant/Environments/Test
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: restaurant-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true